[package]
name = "bottles"
version = "0.1.0"
authors = ["Josh Choo <dev@joshuous.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
